version: '2'
volumes: 
    storage:
services:
  zwift-offline:
    build: .
    ports:
      - 443:443 
      - 80:80 
      - 3022:3022/udp 
      - 3023:3023
    volumes: 
      - 'storage:/usr/src/app/zwift-offline/storage'
